### ISSUE TITLE
YJIT Ruby 3.3 Checklist

### ISSUE THREAD

**Issue by maximecb** [Shopify/ruby#543]
Just a checklist to keep track of all the things we'd like to get done and wrap up in time for the Ruby 3.3 release, to give us an idea of the work that should be completed and make sure we don't forget anything. Most of these tasks are relatively simple, but also not urgent, I assume that many/most of these things will get done in November, after Alan, Kokubun & myself will be back from MPLR.

- [ ] Shrink context down to 16 bytes (Maxime)
- [ ] https://github.com/Shopify/ruby/issues/536
  - Should this be the default? Should people have to opt into code GC instead? (wait for results from Jean)
- [ ] https://github.com/Shopify/ruby/issues/537
- [ ] https://github.com/Shopify/ruby/issues/538
- [ ] Export `rb_yjit_compile_new_iseqs` as boolean for performance
- [ ] https://github.com/Shopify/ruby/issues/539
- [ ] Remove `--yjit-greedy-versioning`, we never use it and it may not even work correctly
- [ ] Go through command-line options, remove anything redundant, update docs
- [ ] Make sure that all benchmarks run correctly. Run them in a loop for a few days?
- [ ] Update the English release notes
- [ ] Make sure that the Japanese release notes are in sync with EN

We should probably aim to complete everything relatively early before the cutoff date (what is the cutoff date for the 3.3 branch?).
